FROM gam2036/aria2  

ENV FTP_SRV "127.0.0.1"
ENV FTP_USR "test"
ENV FTP_PWD "test"
ENV FTP_MNT "/mnt"

RUN apt-get install curlftpfs
 
CMD ["mount $FTP_USR:$FTPPWD@$FTPSRV $FTP_MNT ; aria2c --conf-path=/etc/aria2.conf"]
